export const FETCH_TOPICS_LIST_BEGIN = 'FETCH_TOPICS_LIST_BEGIN';
export const FETCH_TOPICS_LIST_SUCCESS = 'FETCH_TOPICS_LIST_SUCCESS';
export const FETCH_TOPICS_LIST_FAILURE = 'FETCH_TOPICS_LIST_FAILURE';

export const FETCH_PDF_LIST_BEGIN = 'FETCH_PDF_LIST_BEGIN';
export const FETCH_PDF_LIST_SUCCESS = 'FETCH_PDF_LIST_SUCCESS';
export const FETCH_PDF_LIST_FAILURE = 'FETCH_PDF_LIST_FAILURE';

export const FETCH_ESG_SUMMARY_BEGIN = 'FETCH_ESG_SUMMARY_BEGIN';
export const FETCH_ESG_SUMMARY_SUCCESS = 'FETCH_ESG_SUMMARY_SUCCESS';
export const FETCH_ESG_SUMMARY_FAILURE = 'FETCH_ESG_SUMMARY_FAILURE';

export const FETCH_PDF_FILE_BEGIN = 'FETCH_PDF_FILE_BEGIN';
export const FETCH_PDF_FILE_SUCCESS = 'FETCH_PDF_FILE_SUCCESS';
export const FETCH_PDF_FILE_FAILURE = 'FETCH_PDF_FILE_FAILURE';
